<?php
/* 
 * Generated by MegaBuilder v1.0 
 * www.MegaBuilder.com
 */
 
class %%tblname%%_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get %%tblname%% by id
     */
    function get_%%tblname%%($id)
    {
        return $this->db->get_where('%%tblname%%',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all %%tblname%% count
     */
    function get_all_%%tblname%%_count()
    {
        $this->db->from('%%tblname%%');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all %%tblname%%
     */
    function get_all_%%tblname%%($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('%%tblname%%')->result_array();
    }
        
    /*
     * function to add new %%tblname%%
     */
    function add_%%tblname%%($params)
    {
        $this->db->insert('%%tblname%%',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update %%tblname%%
     */
    function update_%%tblname%%($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('%%tblname%%',$params);
    }
    
    /*
     * function to delete %%tblname%%
     */
    function delete_%%tblname%%($id)
    {
        return $this->db->delete('%%tblname%%',array('id'=>$id));
    }
}
